# Generated by Django 4.2.6 on 2023-11-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='choice',
            new_name='choice_text',
        ),
    ]
