# Generated by Django 4.2.6 on 2023-11-13 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_response_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='choice_text',
            new_name='choice',
        ),
    ]
